const CURRENCIES = {
  USD: 'USD',
  CAD: 'CAD',
  MXN: 'MXN',
  EUR: 'EUR',
  GBP: 'GBP',
};

const CURRENCY_DEFAULTS = {
  DEFAULT: CURRENCIES.USD,
  SUPPORTED: [CURRENCIES.USD, CURRENCIES.CAD, CURRENCIES.MXN],
};

module.exports = {
  CURRENCIES,
  CURRENCY_DEFAULTS,
};
