const { CARRIERS } = require('./carriers');

const SERVICE_TYPES = {
  GROUND: 'ground',
  EXPRESS: 'express',
  OVERNIGHT: 'overnight',
  INTERNATIONAL: 'international',
  ECONOMY: 'economy',
  PRIORITY: 'priority',
};

// Carrier-specific service type mappings
const CARRIER_SERVICE_TYPES = {
  [CARRIERS.FEDEX]: {
    [SERVICE_TYPES.GROUND]: 'FEDEX_GROUND',
    [SERVICE_TYPES.EXPRESS]: 'FEDEX_EXPRESS_SAVER',
    [SERVICE_TYPES.OVERNIGHT]: 'FEDEX_STANDARD_OVERNIGHT',
    [SERVICE_TYPES.INTERNATIONAL]: 'INTERNATIONAL_ECONOMY',
  },
  [CARRIERS.UPS]: {
    [SERVICE_TYPES.GROUND]: 'UPS_GROUND',
    [SERVICE_TYPES.EXPRESS]: 'UPS_3_DAY_SELECT',
    [SERVICE_TYPES.OVERNIGHT]: 'UPS_NEXT_DAY_AIR',
    [SERVICE_TYPES.INTERNATIONAL]: 'UPS_WORLDWIDE_EXPEDITED',
  },
  [CARRIERS.USPS]: {
    [SERVICE_TYPES.GROUND]: 'USPS_GROUND_ADVANTAGE',
    [SERVICE_TYPES.EXPRESS]: 'USPS_PRIORITY_MAIL',
    [SERVICE_TYPES.OVERNIGHT]: 'USPS_PRIORITY_MAIL_EXPRESS',
    [SERVICE_TYPES.INTERNATIONAL]: 'USPS_PRIORITY_MAIL_INTERNATIONAL',
  },
  [CARRIERS.DHL]: {
    [SERVICE_TYPES.EXPRESS]: 'DHL_EXPRESS_WORLDWIDE',
    [SERVICE_TYPES.INTERNATIONAL]: 'DHL_ECONOMY_SELECT',
  },
};

module.exports = {
  SERVICE_TYPES,
  CARRIER_SERVICE_TYPES,
};
