const VALIDATION_LIMITS = {
  // Package dimensions
  MAX_WEIGHT_LB: 150,
  MAX_DIMENSION_IN: 108,
  MAX_LENGTH_PLUS_GIRTH: 165,

  // User input
  PASSWORD_MIN_LENGTH: 12,
  EMAIL_MAX_LENGTH: 255,
  NAME_MAX_LENGTH: 100,
  ADDRESS_MAX_LENGTH: 255,

  // Shipment
  MAX_PACKAGES_PER_SHIPMENT: 10,
  MAX_DECLARED_VALUE: 50000,
};

module.exports = {
  VALIDATION_LIMITS,
};
